fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref:  "4.12.0"
    dnsquery:
      repo: "https://github.com/dalen/puppet-dnsquery.git"
      ref: "2.0.1"
  symlinks:
    pe_bulk_agent_install: "#{source_dir}"
